### PR TITLE
Fix for npm ci caching

### LINKED ISSUE #1006: No dependency caching when `npm ci` is used.
**Describe the bug**

This buildpack currently prefers to install modules with `npm ci` over `npm install`. As stated in the [npm docs](https://docs.npmjs.com/cli/v8/commands/npm-ci), `npm ci` completely ignores any existing `node_modules` folder contents. It prefers instead to install from the global npm cache. However, this buildpack still attempts to persist and restore `node_modules` from the buildcache. This means we're using cycles, bandwidth and time caching and restoring artifacts that are completely ignored. Additionally, most builds aren't able to take advantage of any npm artifact caching, making them slower on subsequent builds.

**To Reproduce**
Build any Node.js app that uses npm to install dependencies.

**Versions (please complete the following information):**
 - Heroku Stack: [`heroku-18`, `heroku-20`, `heroku-22`]
 - Node Version: all
 - NPM or Yarn Version: `npm 6+`
 - Buildpack Version: `heroku/nodejs v170` - heroku/nodejs v196

**Additional context**

Caching `node_modules` with `npm install` still works as intended. For folks wishing to speed up builds with caching, set the environment variable `USE_NPM_INSTALL` to `true`.

### PR DESCRIPTION
**Pull request by colincasey**
Since `npm ci` removes any existing `node_modules` folder before installing, to get proper caching behavior we need to cache the npm cache instead.

Fixes #1006

### CODE REVIEW

**Review by doriskwan — APPROVED** [review]

File: lib/cache.sh [hunk 1]
```diff
@@ -48,6 +48,7 @@ restore_default_cache_directories() {
   local build_dir=${1:-}
   local cache_dir=${2:-}
   local yarn_cache_dir=${3:-}
+  local npm_cache="$(npm config get cache)"
```
Comment (joshwlewis) [inline lib/cache.sh:51]: We set `NPM_CONFIG_CACHE` to a `/tmp` dir in `bin/compile`. Reading that is faster and unlikely to error compared to shelling out. Maybe we should use that instead?

Comment (joshwlewis) [reply lib/cache.sh:51]: Since there's a pattern of passing `yarn_cache_dir` in, maybe we should do that for the `npm` version too? I think your a fan of functions with fewer side-effects if I recall =).

Comment (colincasey) [reply lib/cache.sh]: yes, that cleans things up nicely.  i completely missed the `NPM_CONFIG_CACHE` variable until you pointed it out

File: test/run [hunk 2]
```diff
@@ -1419,6 +1419,21 @@ testBinReportYarn() {
...
+testNpmCiCaching() {
+  local cache_dir=$(mktmpdir)
+  compile "ci-caching" $cache_dir
+  assertNotCaptured "Restoring cache"
+  assertCaptured "Caching build"
+  assertCaptured "- npm cache"
+  assertCapturedSuccess
+
+  compile "ci-caching" $cache_dir
+  assertCaptured "Restoring cache"
```
[the remark this answers is not in the document]
Comment (colincasey) [reply test/run:1435]: you can't really tell from the standard output but if `NPM_CONFIG_LOGLEVEL` is set to `http` then i can test that on the first run it hits the network and on the second it does not.  that's been added to the test case.

**Review by joshwlewis — APPROVED** [review]
Looks great!
